@startuml tutorial express
    ' hide the spot
    hide circle

    ' avoid problems with angled crows feet
    skinparam linetype ortho
    
    entity Person {
        ** id: <<PK>> **
        ** name: varchar(128) **
        ** age: integer (3) **
        ** gender: enum (male, female)**
        ** address: varchar(255) **
    }

    relations 

@endstartuml